# Generated by Django 4.1 on 2022-08-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_juego_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juego',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='juego',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
